start prank.s
jiangzhengwenjz/katam pull request #239
Opened 2024-04-15 18:15 UTC by Cofflag

2024-04-15 18:18 UTC, Cofflag commented
Sorry for being so late(•_•)

2024-04-15 20:36 UTC, jiangzhengwenjz requested changes

2024-04-15 20:36 UTC, jiangzhengwenjz commented on src/prank.c
> +                if (!((gRngVal >> 0x10) & 3))
`if (!(Rand16() & 3))`

2024-04-15 20:36 UTC, jiangzhengwenjz commented on src/prank.c
> +                    obj->kirbyAbility = 0xc;
```suggestion
                    obj->kirbyAbility = KIRBY_ABILITY_COOK;
```

2024-04-15 20:36 UTC, jiangzhengwenjz commented on src/prank.c
> +        x = prank->base.x + (s16)temp;
I don't see why temp is unsigned

2024-04-15 20:36 UTC, jiangzhengwenjz commented on src/prank.c
> +        u16 temp = 0x2000;
same here

2024-04-15 20:36 UTC, jiangzhengwenjz commented on src/prank.c
> +            obj->kirbyAbility = 0xc;
```suggestion
            obj->kirbyAbility = KIRBY_ABILITY_COOK;
```

2024-04-16 11:34 UTC, Cofflag commented
https://cexplore.karathan.at/z/OrOsAA
I think this is a fakematch sorry.

2024-04-16 15:56 UTC, jiangzhengwenjz requested changes

2024-04-16 15:56 UTC, jiangzhengwenjz commented on src/prank.c
> +                    prank->base.yspeed = temp1;
```suggestion
                    prank->base.xspeed = 0;
                    prank->base.yspeed = 0;
```

2024-04-16 15:56 UTC, jiangzhengwenjz commented on src/prank.c
> +    if (!temp1)
```suggestion
    prank->base.flags |= 4;
    if (!(prank->base.unk1 & 7))
```

2024-04-17 06:59 UTC, jiangzhengwenjz requested changes

2024-04-17 06:59 UTC, jiangzhengwenjz commented on src/prank.c
> +   if (prank->base.unk62 & 1)
```suggestion
    if (prank->base.unk62 & 1)
```

2024-04-17 18:12 UTC, jiangzhengwenjz requested changes

2024-04-17 18:12 UTC, jiangzhengwenjz commented on src/prank.c
> +    prank->base.flags &= -3;
```suggestion
    prank->base.flags &= ~2;
```

2024-04-17 18:12 UTC, jiangzhengwenjz commented on src/prank.c
> +    prank->base.flags &= -3;
```suggestion
    prank->base.flags &= ~2;
```

2024-04-28 02:10 UTC, jiangzhengwenjz approved these changes

2024-04-28 02:10 UTC, merged

2024-04-28 02:11 UTC, jiangzhengwenjz commented
```
1413968 total bytes of code
967016 bytes of code in src (68.3902%)
446952 bytes of code in asm (31.6098%)
```